name: simple_flutter_application_interactive_cares
description: A simple Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  go_router: ^12.1.1
  firebase_core: ^2.22.0
  flutter_riverpod: ^2.4.8
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  youtube_player_flutter: ^8.1.2
  animate_do: 2.1.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/data/


